package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// Short number metadata is a separate upstream file with its own schema: no
// calling codes, no formats, just the ranges a region reaches with three to
// six digits.

type xmlShortDocument struct {
	Territories []xmlShortTerritory `xml:"territories>territory"`
}

type xmlShortTerritory struct {
	ID                string   `xml:"id,attr"`
	General           *xmlDesc `xml:"generalDesc"`
	ShortCode         *xmlDesc `xml:"shortCode"`
	TollFree          *xmlDesc `xml:"tollFree"`
	PremiumRate       *xmlDesc `xml:"premiumRate"`
	Emergency         *xmlDesc `xml:"emergency"`
	ExpandedEmergency *xmlDesc `xml:"expandedEmergency"`
	StandardRate      *xmlDesc `xml:"standardRate"`
	CarrierSpecific   *xmlDesc `xml:"carrierSpecific"`
	SMSServices       *xmlDesc `xml:"smsServices"`
}

// shortDescNames are the slots emitted for each region, in the order the
// generated struct declares them.
var shortDescNames = []string{
	"General", "ShortCode", "TollFree", "PremiumRate", "Emergency",
	"ExpandedEmergency", "StandardRate", "CarrierSpecific", "SMSServices",
}

type shortTerritory struct {
	Region string
	Descs  map[string]desc
}

// generateShort writes the shortnumber metadata table.
func generateShort(xmlPath, outPath string) error {
	raw, err := os.ReadFile(xmlPath)
	if err != nil {
		return err
	}
	var doc xmlShortDocument
	if err := xml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parsing %s: %w", xmlPath, err)
	}

	terrs := make([]*shortTerritory, 0, len(doc.Territories))
	for i := range doc.Territories {
		x := &doc.Territories[i]
		if x.ID == "" {
			return fmt.Errorf("territory %d has no id", i)
		}
		t := &shortTerritory{Region: x.ID, Descs: map[string]desc{}}
		for name, xd := range map[string]*xmlDesc{
			"General":           x.General,
			"ShortCode":         x.ShortCode,
			"TollFree":          x.TollFree,
			"PremiumRate":       x.PremiumRate,
			"Emergency":         x.Emergency,
			"ExpandedEmergency": x.ExpandedEmergency,
			"StandardRate":      x.StandardRate,
			"CarrierSpecific":   x.CarrierSpecific,
			"SMSServices":       x.SMSServices,
		} {
			d, err := convertDesc(xd)
			if err != nil {
				return fmt.Errorf("territory %s: %s: %w", x.ID, name, err)
			}
			if !d.empty() {
				t.Descs[name] = d
			}
		}
		// The general descriptor carries no possibleLengths upstream. Unlike
		// the main metadata, it does not take the union of everything below
		// it: libphonenumber copies the lengths from the shortCode range
		// alone, because the other ranges are annotations on top of it
		// rather than separate kinds of number. Carrier-specific codes in
		// particular can be longer than any code the region assigns.
		general := t.Descs["General"]
		if len(general.Lengths) == 0 {
			general.Lengths = t.Descs["ShortCode"].Lengths
			t.Descs["General"] = general
		}

		terrs = append(terrs, t)
	}
	sort.Slice(terrs, func(i, j int) bool { return terrs[i].Region < terrs[j].Region })

	sum := sha256.Sum256(raw)
	src, err := renderShort(terrs, sum)
	if err != nil {
		return err
	}
	formatted, err := format.Source(src)
	if err != nil {
		_ = os.WriteFile(outPath+".broken", src, 0o644)
		return fmt.Errorf("formatting generated source: %w (raw output written to %s.broken)", err, outPath)
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s: %d regions (source %s)\n", outPath, len(terrs), hex.EncodeToString(sum[:8]))
	return nil
}

func renderShort(terrs []*shortTerritory, sourceHash [sha256.Size]byte) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by phonexgen from libphonenumber ShortNumberMetadata.xml. DO NOT EDIT.\n\n")
	b.WriteString("package shortnumber\n\n")
	b.WriteString("import \"github.com/bakhod1r/phonex/internal/lazyre\"\n\n")
	b.WriteString("// SourceHash is the SHA-256 of the ShortNumberMetadata.xml this file was\n")
	b.WriteString("// generated from.\n")
	fmt.Fprintf(&b, "const SourceHash = %q\n\n", hex.EncodeToString(sourceHash[:]))

	b.WriteString("// data maps ISO-3166 alpha-2 region codes to their short number ranges.\n")
	b.WriteString("var data = map[string]*Metadata{\n")
	for _, t := range terrs {
		fmt.Fprintf(&b, "\t%q: sn%s,\n", t.Region, t.Region)
	}
	b.WriteString("}\n\n")

	for _, t := range terrs {
		fmt.Fprintf(&b, "var sn%s = &Metadata{\n", t.Region)
		fmt.Fprintf(&b, "\tRegion: %q,\n", t.Region)
		for _, name := range shortDescNames {
			d, ok := t.Descs[name]
			if !ok {
				continue
			}
			fmt.Fprintf(&b, "\t%s: ", name)
			renderShortDesc(&b, name, d)
			b.WriteString(",\n")
		}
		b.WriteString("}\n\n")
	}
	return b.Bytes(), nil
}

func renderShortDesc(b *bytes.Buffer, name string, d desc) {
	b.WriteString("Desc{")
	parts := make([]string, 0, 4)
	if d.Pattern != "" {
		parts = append(parts, fmt.Sprintf("Pattern: %s", lazyFull(d.Pattern)))
		// Emergency numbers are also tested as a prefix, because dialling
		// "112" followed by anything still reaches the emergency service in
		// most countries.
		if name == "Emergency" {
			parts = append(parts, fmt.Sprintf("Prefix: %s", lazyPrefix(d.Pattern)))
		}
	}
	if len(d.Lengths) > 0 {
		parts = append(parts, fmt.Sprintf("Lengths: []int32{%s}", intsJoin(d.Lengths)))
	}
	if d.Example != "" {
		parts = append(parts, fmt.Sprintf("Example: %q", d.Example))
	}
	b.WriteString(strings.Join(parts, ", "))
	b.WriteString("}")
}
